Connect AWS/P5 (H100) instances to CI
NVIDIA/JAX-Toolbox pull request #1133
Opened 2024-10-31 13:47 UTC by olupton

Make use of _test_slurm_pyxis.yaml a little less verbose, and add a new GPU_TYPE input to it. Also change the default to non-exclusive allocation, with exclusive allocation available on request.

2024-10-31 14:03 UTC, mjsML requested changes
This PR is making a massive assumption w.r.t scheduling. IIUC we are tearing down the SLURM cluster in AWS?

2024-11-06 16:56 UTC, yhtang requested changes

2024-11-06 16:56 UTC, yhtang commented on .github/workflows/_test_slurm_pyxis.yaml
> -    secrets:
Why would you remove it? It will make the workflow less adaptable to more clusters.

2024-11-06 16:56 UTC, yhtang commented on .github/workflows/_test_slurm_pyxis.yaml
> +      SLURM_CLUSTER: ${{ inputs.GPU_TYPE == 'A100' && secrets.CLUSTER_LOGIN_USER || secrets.AWS_LOGIN_USER }}@${{ inputs.GPU_TYPE == 'A100' && vars.HOSTNAME_SLURM_LOGIN || vars.HOSTNAME_AWS_SLURM }}
This logic, if necessary, shall be better placed in the calling workflow to maximize reusability of this workflow (which is essentially a function to be called by the master workflow).

2024-11-12 11:41 UTC, closed without merging