Remove 3 jobs: upload_badge, summary, copy_gist.
NVIDIA/JAX-Toolbox pull request #373
Opened 2023-11-13 22:31 UTC by DwarKapex

The `_finalize.yaml` calls 3 reusabel workflows:

1. _upload_badge.yaml
2. _summary.yaml
3. _copy_gist.yaml

These 3 workflows are used only in `_finalyze.yaml`. One easy way to save a few workloads would be to move the contents of those 3 files directly into `_finalyze.yaml`.

Perhaps, they will be used in a future, so let's rename it by adding extra `_` at the beginning of the filename and add deprecation message.

2023-11-14 03:32 UTC, yhtang requested changes
Let's hold on until #371 merges :)

2023-11-14 18:45 UTC, ashors1 approved these changes

2023-11-14 18:49 UTC, terrykong approved these changes

2023-11-27 22:26 UTC, yhtang requested changes

2023-11-27 22:26 UTC, yhtang commented on .github/workflows/_finalize.yaml
> +      # upload badge
This comment is vague. Please extend it to make it more informative. Additionally, for the workflow inputs/outputs section, the `description` field is the perfect place for documentation.

2023-11-27 22:26 UTC, yhtang commented on .github/workflows/_finalize.yaml
> +  action:
Please use separate jobs for each of the reusable workflows that are being replaced.

2023-11-27 22:26 UTC, yhtang commented on .github/workflows/_finalize.yaml
> +      # upload badge
Same comment as above.

2023-11-29 05:00 UTC, DwarKapex commented
Close this PR and create a new one, bc it was partially addressed in `add-pip-compile` PR

2023-11-29 05:00 UTC, closed without merging