lower mem fraction for pax tests to avoid OOM
NVIDIA/JAX-Toolbox pull request #455
Opened 2024-01-09 05:09 UTC by ashors1

Similar to https://github.com/NVIDIA/JAX-Toolbox/pull/431, this PR reduces the amount of memory preallocated to JAX in the nightly Pax tests to prevent NCCL OOM errors.

2024-01-09 17:45 UTC, terrykong commented on .github/workflows/_test_pax.yaml
> +          #SBATCH --export="VOCAB_PATH=gs://t5-data/vocabs/cc_all.32000.100extra/sentencepiece.model,ENROOT_PASSWORD=${{ secrets.GITHUB_TOKEN }},XLA_PYTHON_CLIENT_MEM_FRACTION=0.65"
I think we should move this into the `test-*.sh` scripts themselves:

```sh
export XLA_PYTHON_CLIENT_MEM_FRACTION=${XLA_PYTHON_CLIENT_MEM_FRACTION:-0.65}
```

This way someone would be able to use the same mem fraction is they jumped into the container without having to look at how our CI set it for the SLURM job.

2024-01-09 17:46 UTC, yhtang approved these changes

2024-01-09 17:47 UTC, yhtang requested changes
LGTM but I agree with Terry's suggestion.

2024-01-09 23:37 UTC, ashors1 commented
All Rosetta Pax and ViT tests passed in the presubmit: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/7464961228. @yhtang are we good to merge?

2024-01-09 23:47 UTC, terrykong approved these changes

2024-01-09 23:47 UTC, terrykong commented
LGTM

2024-01-10 07:55 UTC, yhtang approved these changes

2024-01-10 07:55 UTC, merged