Maxtext docker
NVIDIA/JAX-Toolbox pull request #464
Opened 2024-01-10 22:29 UTC by kocchop

Adding support for MaxText to the JAX-toolbox

2024-01-10 23:07 UTC, abhinavgoel95 commented
@terrykong could you review this PR? It adds MaxText support to Jax-Toolbox.

2024-01-10 23:16 UTC, terrykong requested changes

2024-01-10 23:16 UTC, terrykong commented on .github/workflows/_sandbox.yaml
> +name: ~sandbox
just leaving a reminder to revert before merging

2024-01-10 23:16 UTC, terrykong commented on .github/container/Dockerfile.maxtext
> +RUN <<"EOF" bash -ex
Is there a particular reason to keep this out of the central manifest.yaml? Putting it here means that your `latest_verified_commit` won't be bumped by our CI so JAX will move ahead and maxtext will stay where it is.

2024-01-10 23:16 UTC, terrykong commented on .github/container/Dockerfile.maxtext
> +ARG REF_MAXTEXT=main
lines 4-5 & 14-15 aren't needed

2024-01-10 23:18 UTC, terrykong commented
If you'd like one extra guard before enabling building these images in the CI, you could contribute a nightly workflow like this one: https://github.com/NVIDIA/JAX-Toolbox/blob/main/.github/workflows/nightly-pax-build.yaml, except make it run a no-op. Then in a follow up PR you can fill its contents. This is to work around a limitation of Github Actions where you cannot run a workflow that does not exist on the `default` branch, which in our case is `main`

2024-01-11 06:22 UTC, yhtang requested changes
Please add an associated build workflow as @terrykong suggested.

2024-01-12 01:22 UTC, kocchop commented
> If you'd like one extra guard before enabling building these images in the CI, you could contribute a nightly workflow like this one: https://github.com/NVIDIA/JAX-Toolbox/blob/main/.github/workflows/nightly-pax-build.yaml, except make it run a no-op. Then in a follow up PR you can fill its contents and test it. This is to work around a limitation of Github Actions where you cannot run a workflow that does not exist on the `default` branch, which in our case is `main`

2024-01-12 01:24 UTC, kocchop commented
@terrykong @yhtang I have made the necessary changes. I have added a placeholder file for nightly maxtext build. Could you please review and let me know?

2024-01-12 06:46 UTC, terrykong requested changes

2024-01-12 06:46 UTC, terrykong commented on .github/workflows/nightly-maxtext-build.yaml
> +'on': workflow_dispatch
I'm not sure how strict GH actions is, but technically on.workflow_dispatch should be a dict. It doesn't need any args, see the sandbox for an example: https://github.com/NVIDIA/JAX-Toolbox/blob/main/.github/workflows/_sandbox.yaml#L4

2024-01-12 21:32 UTC, terrykong approved these changes

2024-01-12 22:43 UTC, terrykong commented
LGTM

@yhtang any other comments?

2024-01-12 23:09 UTC, abhinavgoel95 submitted a review, later dismissed

2024-01-12 23:47 UTC, yhtang requested changes
Shall we also build it in the presubmit?

Also, I noticed that the Dockerfile is only for amd64. What's the current status for this on arm?

2024-01-13 00:34 UTC, kocchop commented
Hi @yhtang currently there is a tensorflow version mismatch for arm. We may need to create a separate docker file with corresponding wheels. Right now focusing on x86 version to be working. Will work towards the arm build soon

2024-01-16 20:43 UTC, kocchop commented
Hi @yhtang , I have added maxtext to the presubmit CI. I have also tested the dockerfile with sandbox and it is working for amd64. Please let me know if you have any other suggestions.

2024-01-16 21:46 UTC, yhtang approved these changes
LGTM. Note that we need to add tests (smoke, functional, perf, etc.) via subsequent PRs.

2024-01-16 23:35 UTC, merged