Makes rosetta's distribution script library independent
NVIDIA/JAX-Toolbox pull request #53
Opened 2023-05-08 22:20 UTC by terrykong

Change should make it easier to base rosetta on a different base library

2023-05-09 17:25 UTC, yhtang commented
Could you please share a bit about what is 'library independence'?

2023-05-09 17:33 UTC, terrykong commented
> Could you please share a bit about what is 'library independence'?

The change here was to make it so that the `create-distribution.sh` script (formerly `create-t5x-distribution.sh`) could be used to create a different "build" of rosetta. In the future, when someone needs to build a "paxml" or other build of rosetta, they should be able to re-use that script now and just provide different args/patchlist.

2023-05-11 17:49 UTC, yhtang commented
Now I understand that. It required a bit of change in the mindset 😄

2023-05-11 17:55 UTC, terrykong commented
> Now I understand that. It required a bit of change in the mindset 😄

Sorry, I think the phrasing could've been better 😅

2023-05-11 18:13 UTC, yhtang requested changes

2023-05-11 18:13 UTC, yhtang commented on rosetta/create-distribution.sh
> +  echo "[ERROR]: Need to specify the env INSTALLED_DIR="
Since we have the `-d/--dir` option for specifying the installation dir, we could print the error message plus the usage guide here.

2023-05-11 18:13 UTC, yhtang commented on rosetta/create-distribution.sh
> +  function git-extra {
Since this command appends an additional mirror to the git command, would `git+mirror` be more intuitive?

2023-05-11 18:13 UTC, yhtang commented on rosetta/create-distribution.sh
> +for remote in $UPSTREAM_REMOTE_NAME ${EXTRA_REMOTE_NAME:-}; do
Would `${EXTRA_REMOTE_NAME:-}` behave the same as `${EXTRA_REMOTE_NAME}` here?

2023-05-16 17:00 UTC, yhtang commented on rosetta/Dockerfile.t5x
> +RUN rm -rf .git $(find /opt -name "__pycache__")
Thanks for the offline communication. Now I realize that the layers will get flattened later via
```
COPY --from=distribution-builder /opt/t5x /opt/t5x
COPY --from=distribution-builder /opt/rosetta /opt/rosetta
```
So we _can_ reduce final image size this way.

2023-05-16 17:01 UTC, yhtang approved these changes
Good to go 😄

2023-05-16 17:07 UTC, merged