Fix steps/sec computation in Pax tests
NVIDIA/JAX-Toolbox pull request #581
Opened 2024-02-22 23:36 UTC by ashors1

There are currently two issues affecting the reported step times in pax:
1. First `steps/sec` value includes compilation time
2. `steps/sec` computation includes eval step compilation and eval step time

To fix (1), we exclude the first `steps/sec` value from the average step time. To fix (2), we disable eval.

2024-02-22 23:58 UTC, terrykong requested changes

2024-02-22 23:58 UTC, terrykong commented on .github/container/test-pax.sh
> +  EVAL_INTERVAL_STEPS = 100000
Can a comment be added here to explain why it is set this high?

2024-02-23 01:32 UTC, terrykong approved these changes
Assuming CI passes; adding comment shouldn't need retrigger CI

2024-02-26 17:32 UTC, ashors1 commented
> This PR now has a merge conflict due to updates to manifest.yaml, where every package seems to have been updated. Is it necessary for this PR? If not, we can handle version bumps in another PR.

I bumped the manifest because we were seeing a dependency issue with Seqio, so all Pax tests were failing. I tried selectively bumping Seqio, but that did not solve the problem. Since it was not clear to me where exactly the dependency issue was introduced, I tried instead bumping every package in the manifest to see whether that would fix the problem. But if you're wary of this approach, I can investigate more and bump just those packages that fix the Seqio dependency issue.

2024-02-28 18:30 UTC, yhtang commented
> > This PR now has a merge conflict due to updates to manifest.yaml, where every package seems to have been updated. Is it necessary for this PR? If not, we can handle version bumps in another PR.
> 
> I bumped the manifest because we were seeing a dependency issue with Seqio, so all Pax tests were failing. I tried selectively bumping Seqio, but that did not solve the problem. Since it was not clear to me where exactly the dependency issue was introduced, I tried instead bumping every package in the manifest to see whether that would fix the problem. But if you're wary of this approach, I can investigate more and bump just those packages that fix the Seqio dependency issue.

The downside of bumping manifests alongside other changes is that, as what has happened here, that the PR may remain active for a few days while the upstream manifest evolved. Ideally, if we can fix Pax tests via another PR and then only do changes related to the steps/second measurements in this PR that'll be much more secure.

2024-02-28 21:34 UTC, yhtang approved these changes

2024-02-28 22:05 UTC, terrykong approved these changes

2024-02-28 22:05 UTC, merged

2024-03-05 09:53 UTC, olupton commented
FWIW this PR contained an incomplete update to the manifest: it updated the `xla` commit without updating the dependent `openxla-triton` commit and patches. `bump.sh` is supposed to call `bump-openxla-triton.sh` and take care of this. I don't know what happened in this instance.