Triton: use CUDA 12.3 tools from the base image
NVIDIA/JAX-Toolbox pull request #656
Opened 2024-03-22 11:57 UTC by olupton

Previously, Triton would download its own copies of `ptxas`, `cuobjdump` and `nvdisasm`:
https://github.com/openxla/triton/blob/cl617459344/python/setup.py#L373-L393

This began to cause problems when those versions were bumped to CUDA 12.4, meaning that Triton started to generate PTX with version number 8.3. When this was compiled, using the `ptxas` from the base container, inside XLA, then there were errors:
```
CustomCall failed: ptxas exited with non-zero error code 65280, output: ptxas /tmp/tempfile-aac66f5d464c-1e8add55-32-61414d9c202e5, line 5;
fatal   : Unsupported .version 8.4; current version is '8.3'
ptxas fatal   : Ptx assembly aborted due to errors
```
in the nightly tests, which are taken from JAX-Triton.

Setting environment variables like `TRITON_PTXAS_PATH` has two effects:
- it blocks downloading other versions during `setup.py`
- at runtime, it is the highest precedence search location

If Triton starts depending on new fixes before the base container is updated to CUDA 12.4, problems may resurface.

Thanks to @andportnoy for help debugging.

2024-03-22 13:15 UTC, yhtang requested changes
Given that the paths are hard-coded, can we add some test so that we get notified if the binaries change locations? e.g.
```
RUN if [[ ! -x ${TRITON_PTXAS_PATH} ]]; then <THROW-ERROR>; fi
```

2024-03-22 16:09 UTC, andportnoy submitted a review, later dismissed
Thank you for the fix! Left a minor suggestion adding some context.

2024-03-22 16:26 UTC, nouiz commented
Should we fix this upstream?

________________________________
From: Andrey Portnoy ***@***.***>
Sent: Friday, March 22, 2024 9:09:38 AM
To: NVIDIA/JAX-Toolbox ***@***.***>
Cc: Frederic Bastien ***@***.***>; Review requested ***@***.***>
Subject: Re: [NVIDIA/JAX-Toolbox] Triton: use CUDA 12.3 tools from the base image (PR #656)


@andportnoy approved this pull request.

Thank you for the fix! Left a minor suggestion adding some context.

________________________________

In .github/container/Dockerfile.triton<https://github.com/NVIDIA/JAX-Toolbox/pull/656#discussion_r1535831398>:

> @@ -2,10 +2,18 @@
 ARG BASE_IMAGE=ghcr.io/nvidia/jax-mealkit:jax
 ARG SRC_PATH_TRITON=/opt/openxla-triton

+FROM ${BASE_IMAGE} as base
+# Tell Triton to use CUDA binaries from the host container. These should be set


⬇️ Suggested change

-# Tell Triton to use CUDA binaries from the host container. These should be set
+# Triton setup.py downloads and installs CUDA binaries at specific versions
+# hardcoded in the script itself:
+# https://github.com/openxla/triton/blob/84f9d9de158fb866fac67970f0f5d323999d9db1/python/setup.py#L373-L393
+# Tell Triton to use CUDA binaries from the host container instead. These should be set


—
Reply to this email directly, view it on GitHub<https://github.com/NVIDIA/JAX-Toolbox/pull/656#pullrequestreview-1955208951>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AABMF627MQCSEU6JBTO5DBDYZRJUFAVCNFSM6AAAAABFDGANMOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNJVGIYDQOJVGE>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-03-22 16:42 UTC, andportnoy submitted a review, later dismissed
Great suggestion, Andrey. Good job.

2024-03-22 22:52 UTC, yhtang requested changes

2024-03-22 22:52 UTC, yhtang commented on .github/container/Dockerfile.triton
> +RUN [ -f "${TRITON_PTXAS_PATH}" ] && [ -f "${TRITON_CUOBJDUMP_PATH}" ] && [ -f "${TRITON_NVDISASM_PATH}" ]
Why use `-f` instead of `-x`?
-f: True if FILE exists and is a regular file.
-x: True if FILE exists and is executable.

2024-03-25 11:54 UTC, olupton commented
@nouiz
> Should we fix this upstream?

I'm not sure what that would look like? What did you have in mind?

2024-03-25 17:10 UTC, yhtang approved these changes

2024-03-25 17:21 UTC, merged

2024-03-25 20:51 UTC, nouiz commented
> @nouiz
> 
> > Should we fix this upstream?
> 
> I'm not sure what that would look like? What did you have in mind?

I taught it was for Triton via Pallas. All is good.