Combine all workflow metrics into single summary
NVIDIA/JAX-Toolbox pull request #666
Opened 2024-03-27 20:38 UTC by CliveUnger

Combine sitrep, status, and metric_summary for each test into a single summary json at the end.

The goal is capturing a complete picture of a Workflow Run: each build success/fail, each test success/fail, the metrics for each test and also metadata like what image the tests ran on and such. This data should be all pulled from a single artifact file.

2024-03-28 02:32 UTC, CliveUnger commented
I have an example in sandbox of this working here: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/8461564960

There are some caveats: 
- The `metrics_summary.json` isn't included since in the sandbox I am reusing artifacts from an existing worfklow.
- The artifact path was hardcoded. This would be fixed before merging.

2024-04-01 05:29 UTC, yhtang requested changes

2024-04-08 21:48 UTC, CliveUnger commented on .github/workflows/_finalize.yaml
> +            dirName=$(basename $dir) && [ -d "$dir" ] || continue
Fixed.

2024-04-08 21:49 UTC, CliveUnger commented
Do I need to revert the changes to `_sandbox.yaml` before this goes in?

2024-04-09 21:28 UTC, CliveUnger commented
I am running a full "CI" workflow on this change here: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/8620819287

If this completes successfully, this PR should be good to go.

2024-04-11 23:06 UTC, CliveUnger commented
Closing, will re-open from repo branch.

2024-04-11 23:06 UTC, closed without merging