fix patch for upstream maxtext
NVIDIA/JAX-Toolbox pull request #699
Opened 2024-04-08 21:17 UTC by kocchop

Most of the patch change PRs got merged to maxtext main. So removing them from patch. Only change require now is the tf pin

2024-04-09 05:43 UTC, terrykong requested changes
Does the changes to the dockerfile need to be reverted as well? https://github.com/NVIDIA/JAX-Toolbox/blob/main/.github/container/Dockerfile.maxtext.amd64#L23

2024-04-09 08:55 UTC, olupton commented
> Does the changes to the dockerfile need to be reverted as well? https://github.com/NVIDIA/JAX-Toolbox/blob/main/.github/container/Dockerfile.maxtext.amd64#L23

Note that the patch file is not being deleted here, there is just a large block being removed from the top of it.

2024-04-09 19:30 UTC, kocchop commented
@terrykong @olupton I bumped the maxtext commit id in `manifest.yaml`. We still need patch for the tensorflow pin.

2024-04-10 11:31 UTC, olupton approved these changes

2024-04-12 15:51 UTC, terrykong approved these changes

2024-04-12 18:05 UTC, merged