Vkozlov/remove grok
NVIDIA/JAX-Toolbox pull request #975
Opened 2024-08-02 18:32 UTC by DwarKapex

2024-08-08 22:07 UTC, terrykong requested changes
It looks like this PR also removed pax patch files and their reference in the manifest for some reason. Could you confirm if that was intentional?

2024-08-12 23:45 UTC, DwarKapex commented
> It looks like this PR also removed pax patch files and their reference in the manifest for some reason. Could you confirm if that was intentional?

I tried to remove everything, that has any connection to Grok. For instance, [paxml/PR-93.patch](https://github.com/NVIDIA/JAX-Toolbox/pull/975/files#diff-3b070c4c1860231e93952bd8730ebf2e0b3aa521473fc74838bf8cf23ec3c5b2) updates the Grok classes. I'm under impression, that this is to support Grok.
Also [praxis/PR-74.patch](https://github.com/NVIDIA/JAX-Toolbox/pull/975/files#diff-b6ca750e56dd219c7508818315fa787af2e79eddccf905c3a5c9b187ea1520ca) does some patches for Grok, but I'm not entirely sure I need to remove the whole patch or to do it partially.
WDYT?

2024-08-13 00:48 UTC, terrykong requested changes
You can revert/leave the pax stuff. The patches are orthogonal to the grok container since that's a different codebase entirely.

2024-08-13 00:48 UTC, terrykong commented on .github/container/manifest.yaml
> -    pull/93/head: file://patches/paxml/PR-93.patch # exposes TE DPA argument in Grok to make it configurable from the command line
You can revert this

2024-08-13 00:48 UTC, terrykong commented on .github/container/manifest.yaml
> -    pull/74/head: file://patches/praxis/PR-74.patch # experimental support for using TE FMHA in GQA
you can revert this

2024-08-13 00:48 UTC, terrykong commented on .github/container/patches/paxml/PR-93.patch
you can revert deleting this

2024-08-13 00:48 UTC, terrykong commented on .github/container/patches/praxis/PR-74.patch
you can revert deleting this

2024-08-14 10:31 UTC, olupton approved these changes

2024-08-14 10:32 UTC, merged